More experimental changes - better error messages

diff --git a/experimental/pam_script_auth b/experimental/pam_script_auth
--- a/experimental/pam_script_auth
+++ b/experimental/pam_script_auth
@@ -1,6 +1,15 @@
 #!/bin/bash
+# Descriptive failure
+function fail {
+    echo $* > /etc/601/message
+    exit 1
+}
+
 # Attempt to login to cat-soop
-SID=`(echo $PAM_USER; echo $PAM_AUTHTOK) | /etc/601/catlogin.py` || exit 1
+ping -c 1 sicp-s4.mit.edu &> /dev/null || fail Unable to connect to cat-soop server
+
+# In case of error here, 
+SID=`(echo $PAM_USER; echo $PAM_AUTHTOK) | /etc/601/catlogin.py` || fail Incorrect Password
 # We've succeeded on the login!
 # Add user. If we are here, then this is a cat-soop user.
 useradd -s /bin/bash $PAM_USER -d /home/$PAM_USER -K UID_MIN=10000 2> /dev/null
@@ -8,21 +17,21 @@ useradd -s /bin/bash $PAM_USER -d /home/$PAM_USER -K UID_MIN=10000 2> /dev/null
 touch /etc/601/logins/$PAM_USER.lock
 
 # Create directory which will have unencrypted data
-install -m700 -o $PAM_USER -g $PAM_USER -d /home/$PAM_USER || exit 1
+install -m700 -o $PAM_USER -g $PAM_USER -d /home/$PAM_USER || fail Failure creating home
 
 ###### START ORIFS STUFF HERE INSTEAD LATER ######
 if [ ! -e /etc/601/ori/$PAM_USER ]
 then
-    [ -n `mount | grep -w /home/$PAM_USER` ] || exit 1
+    [ -n `mount | grep -w /home/$PAM_USER` ] || fail Home already mounted, no syncing FS
     # Let's create the directory which will have the encrypted data
-    install -m700 -o $PAM_USER -g $PAM_USER -d /etc/601/ori/$PAM_USER || exit 1
+    install -m700 -o $PAM_USER -g $PAM_USER -d /etc/601/ori/$PAM_USER || fail Failure syncing
     # Let's encrypt it!
     ( echo; echo $PAM_AUTHTOK; echo $PAM_AUTHTOK; ) | \
-	encfs -S /etc/601/ori/$PAM_USER /home/$PAM_USER &> /dev/null || exit 1
+	encfs -S /etc/601/ori/$PAM_USER /home/$PAM_USER &> /dev/null || fail Failure on encryption
     # Fill it with skel
     cp -r /etc/skel/. /home/$PAM_USER
     chown -R $PAM_USER:$PAM_USER /home/$PAM_USER
-    fusermount -u /home/$PAM_USER || exit 1
+    fusermount -u /home/$PAM_USER || fail Failure unmounting home
 fi
 ###### END ORIFS STUFF HERE INSTEAD LATER ######
 
@@ -32,7 +41,7 @@ chown -R $PAM_USER:$PAM_USER /etc/601/ori/$PAM_USER
 # Mount home directory it not mounted already
 if [ -n `mount | grep -w /home/$PAM_USER` ]
 then
-    echo $PAM_AUTHTOK | sudo -u $PAM_USER encfs -S /etc/601/ori/$PAM_USER /home/$PAM_USER -- -o allow_other || exit 1
+    echo $PAM_AUTHTOK | sudo -u $PAM_USER encfs -S /etc/601/ori/$PAM_USER /home/$PAM_USER -- -o allow_other || fail Failure mounting home
 fi
 
 # Setup firefox profile
